---
title: "211014_TOC_sample_size_test"
author: "KiseokUchicago"
date: "2021-10-14"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=11, fig.height=9,
                      error=TRUE, echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE)
```

## TOC(Total organic carbon) measurements
Researcher: **Kiseok Lee** \
Experiment Date: 9/11/21 \
Analysis Date: 10/13/21
Lab: **Seppe Kuehn**

```{r}
# libraries
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(vegan)
library(tidyverse)
library(magrittr)
library(readxl)
library(reshape2)
library(gtools)
library(devtools)
library(openxlsx)
library(ape)
library(stringr)
library(tidyr)
library(ggrepel)
library(ggpubr)

## theme for ggplot
mytheme <- theme_bw() + 
  theme(text = element_text(family="serif")) +
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=10, family="serif"))+
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank(),panel.background=element_blank(),panel.border=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))

mytheme_2d <- theme_bw() + 
  theme(text = element_text(family="serif")) +
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=13, family="serif"))+
  # theme(panel.grid.major = element_blank()) +
  # theme(panel.grid.minor = element_blank(),panel.background=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))


# color collection
my_color_collection <- c(
  "#CBD588", "#5F7FC7", "orange", "#AD6F3B", "#673770", 
  "#D14285", "#652926", "#C84248", "#8569D5", "#5E738F",
  "#D1A33D", "#8A7C64", "#599861","#616163", "#FFCDB2",
  "#6D9F71", "#242F40",
  "#CCA43B", "#F92A82", "#ED7B84", "#7EB77F", 
  "#DEC4A1", "#E5D1D0", '#0E8482', '#C9DAEA', '#337357', 
  '#95C623', '#E55812', '#04471C', '#F2D7EE', '#D3BCC0', 
  '#A5668B', '#69306D', '#0E103D', '#1A535C', '#4ECDC4', 
  '#F7FFF7', '#FF6B6B', '#FFE66D', '#6699CC', '#FFF275', 
  '#FF8C42', '#FF3C38', '#A23E48', '#000000', '#CF5C36', 
  '#EEE5E9', '#7C7C7C', '#EFC88B', '#2E5266', '#6E8898', 
  '#9FB1BC', '#D3D0CB', '#E2C044', '#5BC0EB', '#FDE74C', 
  '#9BC53D', '#E55934', '#FA7921', "#CD9BCD", "#508578", "#DA5724")

# for git push, use this instead of using wflow_git_push()
# git push -u origin master (in the Git app / in the working directory)

```

## 1. Import data table from python code
```{r}
# import file
# 10ul
df_10ul <- openxlsx::read.xlsx("data/210927_TOC_sample_plate1_10ul.xlsx")
df_100ul <- openxlsx::read.xlsx("data/210927_TOC_sample_plate1_100ul.xlsx")
dim(df_10ul)
dim(df_100ul)

df_10ul <- df_10ul %>% filter(Sample_ml == 0.01)
df_100ul <- df_100ul %>% filter(Sample_ml == 0.1)
dim(df_10ul)
dim(df_100ul)

df_p1 <- rbind(df_10ul, df_100ul)
head(df_p1)
colnames(df_p1)
dim(df_p1)

# remove NA
dim(df_p1)
df_p1 <- na.omit(df_p1)
dim(df_p1)

# remove wells H06, H09
# df_p %<>% filter(!(Well %in% c("H06","H09")))
# dim(df_p)

```

## 2. Preprocess data and select datapoints to visualize
```{r}
## convert TOC according to dilutions (mg to percent TOC)
df_percent <- df_p1 %>% mutate(TOC_percent = (TOC_ppm * Buffer_ml * 0.001 * 100) / (Soil_weight))

colnames(df_percent)
# average technical replicate
df_ave <- df_percent %>% group_by(Sample, Sample_type, Buffer) %>% summarise(Ave_TOC_percent = mean(TOC_percent), Std_TOC_percent = sd(TOC_percent)) %>% ungroup()

```

## 3.1. Filter and buffer testing
```{r}
# (1) Compare Just the Original samples
df_method <- df_ave %>% filter(Sample_type %in% c("Filtered","Whatman")) 

ggplot(df_method, aes(x=Buffer, y=Ave_TOC_percent, color=Sample_type, group=Sample_type)) +
  geom_point(size=2.5, shape=21) +
  geom_line(size=1)+
  geom_errorbar(aes(ymin=Ave_TOC_percent - Std_TOC_percent, ymax=Ave_TOC_percent + Std_TOC_percent), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("TOC (% weight) \n") +
  xlab("\n Extraction buffer") +
  #scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  ggtitle("Effect of Filter method, and Extraction buffer (TOC) \n") +
  # label
  geom_text(aes(label = round(Ave_TOC_percent,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d
```

## 3.2. Used sample amount
```{r}
df_spike <- df_ave %>% filter(Sample_type %in% c("Control","Spike_in")) 

# df_spike$Sample <- str_replace(df_spike$Sample, "Control_H2O_","")
# df_spike$Sample <- str_replace(df_spike$Sample, "Spike_in_H2O_","")
df_spike$Sample <- factor(df_spike$Sample, levels= c("Control_H2O_100ul","Spike_in_H2O_100ul", "Control_H2O_10ul", "Spike_in_H2O_10ul"))

df_spike$Sample_ml <- df_spike$Sample
df_spike$Sample_ml <- str_replace(df_spike$Sample_ml, "Control_H2O_","")
df_spike$Sample_ml <- str_replace(df_spike$Sample_ml, "Spike_in_H2O_","")

ggplot(df_spike, aes(x=Sample, y=Ave_TOC_percent, color=Sample_ml, group=Sample_ml)) +
  geom_point(size=2.5, shape=21) +
  geom_line(size=1)+
  geom_errorbar(aes(ymin=Ave_TOC_percent - Std_TOC_percent, ymax=Ave_TOC_percent + Std_TOC_percent), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("TOC (% weight) \n") +
  xlab("\n Sample") +
  #scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  ggtitle("Effect of Sample amount and digestion platform (TOC) \n") +
  # label
  geom_text(aes(label = round(Ave_TOC_percent,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d


```


## 4. UMN (Minnesota) data 

```{r}

df_ext <- openxlsx::read.xlsx("data/TOC_TN_measurement_2_labs_211014.xlsx")

## (1) TOC drying temperature effect
df_temp <- df_ext %>% filter(Lab == "UMN") %>% select(-TN_percent)
df_temp <- na.omit(df_temp)
dim(df_temp)

df_temp$Dry_temp <- factor(df_temp$Dry_temp)


ggplot(df_temp, aes(x=Dry_temp, y=TOC_percent)) +
  geom_point(size=2.5, shape=16, color="maroon2") +
  # geom_line(size=1)+
  # geom_errorbar(aes(ymin=Ave_TOC_percent - Std_TOC_percent, ymax=Ave_TOC_percent + Std_TOC_percent), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("TOC (% weight) \n") +
  xlab("\n Drying oven temperature") +
  scale_y_continuous(breaks = seq(3.5,4.5,0.25), limits=c(3.5, 4.5))+
  ggtitle("Effect of drying oven temperature \n") +
  # label
  geom_text(aes(label = round(TOC_percent,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

## (2) TOC between labs
df_toc_lab <- df_ext %>% select(-TN_percent) %>% filter(Dry_temp == 105)

ggplot(df_toc_lab, aes(x=Lab, y=TOC_percent)) +
  geom_point(size=2.5, shape=16, color="maroon2") +
  # geom_line(size=1)+
  # geom_errorbar(aes(ymin=Ave_TOC_percent - Std_TOC_percent, ymax=Ave_TOC_percent + Std_TOC_percent), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("TOC (% weight) \n") +
  xlab("\n Analysis lab") +
  scale_y_continuous(breaks = seq(3.5,4.5,0.25), limits=c(3.5, 4.5))+
  ggtitle("Comparison between labs (Identical 105C dried, 150um sieved soil) \n") +
  # label
  geom_text(aes(label = round(TOC_percent,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d


## (3) TN between labs
df_tn_lab <- df_ext %>% select(-TOC_percent)
df_tn_lab <- na.omit(df_tn_lab)

ggplot(df_tn_lab, aes(x=Lab, y=TN_percent)) +
  geom_point(size=2.5, shape=16, color="red") +
  # geom_line(size=1)+
  # geom_errorbar(aes(ymin=Ave_TOC_percent - Std_TOC_percent, ymax=Ave_TOC_percent + Std_TOC_percent), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("Total Nitrogen (% weight) \n") +
  xlab("\n Analysis lab") +
  scale_y_continuous(breaks = seq(0.3,0.4,0.05), limits=c(0.3, 0.4))+
  ggtitle("Comparison between labs (Identical 105C dried, 150um sieved soil) \n") +
  # label
  geom_text(aes(label = round(TN_percent,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

```




