---
title: "220113_pH_while_perturbation"
author: "KiseokUchicago"
date: "2022-01-16"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r global_options, include=FALSE}
library(knitr)
knitr::opts_chunk$set(fig.width=11, fig.height=9,
                      error=TRUE, echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE,
                      tidy.opts=list(width.cutoff=40),tidy=TRUE)
```

## Time series analysis - pH perturbation (pH perturbation)
Researcher: **Kiseok Lee** \
Experiment Date: 12/29/21 - 1/3/22 (3 days) \
Analysis Date: 1/17/21
Lab: **Seppe Kuehn**

```{r}
# libraries
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(vegan)
library(tidyverse)
library(magrittr)
library(readxl)
library(reshape2)
library(gtools)
library(devtools)
library(openxlsx)
library(ape)
library(stringr)
library(tidyr)
library(ggrepel)
library(ggpubr)

## theme for ggplot
mytheme <- theme_bw() + 
  theme(text = element_text(family="serif")) +
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=10, family="serif"))+
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank(),panel.background=element_blank(),panel.border=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))

mytheme_2d <- theme_bw() + 
  theme(text = element_text(family="serif")) +
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=13, family="serif"))+
  # theme(panel.grid.major = element_blank()) +
  # theme(panel.grid.minor = element_blank(),panel.background=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))


# color collection
my_color_collection <- c(
  "#CBD588", "#5F7FC7", "orange", "#AD6F3B", "#673770", 
  "#D14285", "#652926", "#C84248", "#8569D5", "#5E738F",
  "#D1A33D", "#8A7C64", "#599861","#616163", "#FFCDB2",
  "#6D9F71", "#242F40",
  "#CCA43B", "#F92A82", "#ED7B84", "#7EB77F", 
  "#DEC4A1", "#E5D1D0", '#0E8482', '#C9DAEA', '#337357', 
  '#95C623', '#E55812', '#04471C', '#F2D7EE', '#D3BCC0', 
  '#A5668B', '#69306D', '#0E103D', '#1A535C', '#4ECDC4', 
  '#F7FFF7', '#FF6B6B', '#FFE66D', '#6699CC', '#FFF275', 
  '#FF8C42', '#FF3C38', '#A23E48', '#000000', '#CF5C36', 
  '#EEE5E9', '#7C7C7C', '#EFC88B', '#2E5266', '#6E8898', 
  '#9FB1BC', '#D3D0CB', '#E2C044', '#5BC0EB', '#FDE74C', 
  '#9BC53D', '#E55934', '#FA7921', "#CD9BCD", "#508578", "#DA5724")

# for git push, use this instead of using wflow_git_push()
# git push -u origin master (in the Git app / in the working directory)

# for making pdf file
library(rmarkdown)
# render("analysis/~~.Rmd", "pdf_document")
```


## 1. 1ul of 0.05M HCl or 0.05M NaOH was incrementally added
```{r}
df_pH_T0 <- openxlsx::read.xlsx("data/220113_pH_colorimetric_T0.xlsx")  # I ruined the Allandale sample in this plate
df_pH_T2 <- openxlsx::read.xlsx("data/220113_pH_colorimetric_T2.xlsx")
df_pH_T3 <- openxlsx::read.xlsx("data/220113_pH_colorimetric_T3.xlsx")
df_pH_T8 <- openxlsx::read.xlsx("data/220113_pH_colorimetric_T8.xlsx")
df_pH_T12 <- openxlsx::read.xlsx("data/220113_pH_colorimetric_T12.xlsx")

dim(df_pH_T0)
dim(df_pH_T2)
dim(df_pH_T3)
dim(df_pH_T8)
dim(df_pH_T12)

# filter wells with too much soil
df_pH_T0 %<>% filter(!(Well %in% c("A08","B08","D08","F08","D09","E09","F09","E10"))) # too much soil in well


df_time <- openxlsx::read.xlsx("data/220103_time_table.xlsx")
df_time$Time_hours <- round(df_time$Time_hours, 1)
df_time$Time_days <- round(df_time$Time_days, 2)

df_pH_T <- rbind(df_pH_T0, df_pH_T2, df_pH_T3, df_pH_T8, df_pH_T12)
df_pH_T %<>% left_join(df_time, by=c("Time_point"="Time_point"))
dim(df_pH_T)

# Change the soil names to include pH
df_pH_T$Soil <- str_replace(df_pH_T$Soil,"NicholsC","NicholsC_pH7")
df_pH_T$Soil <- str_replace(df_pH_T$Soil,"Allandale","Allandale_pH4")
df_pH_T$Soil <-  factor(df_pH_T$Soil, levels = c("NicholsC_pH7", "Allandale_pH4"))

# mols and molarity unit conversion
# test
df_pH <- df_pH_T %>% filter(Titration_type %in% c("NaOH","HCl"))
dim(df_pH) # 450 -> 390
Added_Volume <- 1.7 # ml
moisture_percent_1 = 19 # NicholsC
moisture_percent_2 = 33.2 # Allandale
df_pH$Added_ul <- ifelse(df_pH$Titration_type == "NaOH", -1*df_pH$Added_ul, df_pH$Added_ul) # HCl is +, NaOH is -
df_pH %<>% mutate(H_mol = Concentration_M * Added_ul * 10^(-6)) # Calculate H mol 
df_pH$Volume <- ifelse(df_pH$Soil == "NicholsC_pH7", Added_Volume + Soil_mg*(moisture_percent_1/100), 0) # Calc total volume
df_pH$Volume <- ifelse(df_pH$Soil == "Allandale_pH4", Added_Volume + Soil_mg*(moisture_percent_2/100), df_pH$Volume) # Calc total volume
# df_pH$Volume %>% unique()
df_pH %<>% mutate(H_Molarity = H_mol / (Volume * 10^(-3)))
df_pH %<>% mutate(H_mM = H_Molarity * 1000)
# openxlsx::write.xlsx(df_pH, "df_pH.xlsx")

# how many levels of H_mM?
pH_pert <- df_pH %>% select(H_mM) %>% unique() %>% arrange()
df_pH %>% filter(Soil == "NicholsC_pH7")%>% select(H_mM) %>% unique() %>% arrange()
df_pH %>% filter(Soil == "Allandale_pH4")%>% select(H_mM) %>% unique() %>% arrange()
colnames(df_pH)

# average the pH
df_pH_ave <- df_pH %>% group_by(Nitrite_input, Nitrate_input, Soil, Titration_type, Concentration_M, Added_ul, Sample_type, H_mol, H_Molarity, H_mM, Time_point, Time_minutes, Time_hours, Time_days) %>% summarise(Ave_pH = mean(pH_colorimetric), Std_pH = sd(pH_colorimetric)) %>% ungroup()

colnames(df_pH_ave)

```

Plot one time point at the time
```{r}
df_time
# 1 time point # mol
df_T0 <- df_pH_ave %>% filter(Time_point == "T0")

ggplot(df_T0, aes(x=H_mM, y=Ave_pH, color=Soil, group=Soil)) +
  geom_point(size=3, shape=16, alpha=1) +
  geom_errorbar(aes(ymin=Ave_pH - Std_pH, ymax=Ave_pH + Std_pH), width=.05)+
  geom_line(size=1)+
  # scale_color_brewer(palette='Set1') +
  ylab("pH \n") +
  xlab("\n added [H+] mM") +
  scale_y_continuous(breaks = seq(0,12,1), limits=c(0, 12))+
  ggtitle("[0hr] Soil pH perturbation (Anaerobic incubation) \n") +
  # label
  # geom_text(aes(label = pH_colorimetric), size = 3, vjust = -1.5, family="serif", show.legend  = FALSE)+
  mytheme_2d

df_T2 <- df_pH_ave %>% filter(Time_point == "T2")

ggplot(df_T2, aes(x=H_mM, y=Ave_pH, color=Soil, group=Soil)) +
  geom_point(size=3, shape=16, alpha=1) +
  geom_errorbar(aes(ymin=Ave_pH - Std_pH, ymax=Ave_pH + Std_pH), width=.05)+
  geom_line(size=1)+
  # scale_color_brewer(palette='Set1') +
  ylab("pH \n") +
  xlab("\n added [H+] mM") +
  scale_y_continuous(breaks = seq(0,12,1), limits=c(0, 12))+
  ggtitle("[6.8hr] Soil pH perturbation (Anaerobic incubation) \n") +
  # label
  # geom_text(aes(label = pH_colorimetric), size = 3, vjust = -1.5, family="serif", show.legend  = FALSE)+
  mytheme_2d

df_T3 <- df_pH_ave %>% filter(Time_point == "T3")

ggplot(df_T3, aes(x=H_mM, y=Ave_pH, color=Soil, group=Soil)) +
  geom_point(size=3, shape=16, alpha=1) +
  geom_errorbar(aes(ymin=Ave_pH - Std_pH, ymax=Ave_pH + Std_pH), width=.05)+
  geom_line(size=1)+
  # scale_color_brewer(palette='Set1') +
  ylab("pH \n") +
  xlab("\n added [H+] mM") +
  scale_y_continuous(breaks = seq(0,12,1), limits=c(0, 12))+
  ggtitle("[19hr] Soil pH perturbation (Anaerobic incubation) \n") +
  # label
  # geom_text(aes(label = pH_colorimetric), size = 3, vjust = -1.5, family="serif", show.legend  = FALSE)+
  mytheme_2d

df_T8 <- df_pH_ave %>% filter(Time_point == "T8")

ggplot(df_T8, aes(x=H_mM, y=Ave_pH, color=Soil, group=Soil)) +
  geom_point(size=3, shape=16, alpha=1) +
  geom_errorbar(aes(ymin=Ave_pH - Std_pH, ymax=Ave_pH + Std_pH), width=.05)+
  geom_line(size=1)+
  # scale_color_brewer(palette='Set1') +
  ylab("pH \n") +
  xlab("\n added [H+] mM") +
  scale_y_continuous(breaks = seq(0,12,1), limits=c(0, 12))+
  ggtitle("[43hr] Soil pH perturbation (Anaerobic incubation) \n") +
  # label
  # geom_text(aes(label = pH_colorimetric), size = 3, vjust = -1.5, family="serif", show.legend  = FALSE)+
  mytheme_2d

df_T12 <- df_pH_ave %>% filter(Time_point == "T12")

ggplot(df_T12, aes(x=H_mM, y=Ave_pH, color=Soil, group=Soil)) +
  geom_point(size=3, shape=16, alpha=1) +
  geom_errorbar(aes(ymin=Ave_pH - Std_pH, ymax=Ave_pH + Std_pH), width=.05)+
  geom_line(size=1)+
  # scale_color_brewer(palette='Set1') +
  ylab("pH \n") +
  xlab("\n added [H+] mM") +
  scale_y_continuous(breaks = seq(0,12,1), limits=c(0, 12))+
  ggtitle("[74hr] Soil pH perturbation (Anaerobic incubation) \n") +
  # label
  # geom_text(aes(label = pH_colorimetric), size = 3, vjust = -1.5, family="serif", show.legend  = FALSE)+
  mytheme_2d

```

Acidic soil and neutral soil separately
```{r}
df_nic <- df_pH_ave %>% filter(Soil == "NicholsC_pH7")
df_nic$Time_hours <- factor(df_nic$Time_hours)

ggplot(df_nic, aes(x=H_mM, y=Ave_pH, color=Time_hours, group=Time_hours)) +
  geom_point(size=3, shape=16, alpha=1) +
  geom_errorbar(aes(ymin=Ave_pH - Std_pH, ymax=Ave_pH + Std_pH), width=.05)+
  geom_line(size=1)+
  # scale_color_brewer(palette='Set1') +
  ylab("pH \n") +
  xlab("\n added [H+] mM") +
  scale_y_continuous(breaks = seq(0,12,1), limits=c(0, 12))+
  ggtitle("Neutral Soil pH perturbation (NicholsC: pH 7) \n") +
  # label
  # geom_text(aes(label = pH_colorimetric), size = 3, vjust = -1.5, family="serif", show.legend  = FALSE)+
  mytheme_2d

# Acidic soil
df_al <- df_pH_ave %>% filter(Soil == "Allandale_pH4")
df_al$Time_hours <- factor(df_al$Time_hours)

ggplot(df_al, aes(x=H_mM, y=Ave_pH, color=Time_hours, group=Time_hours)) +
  geom_point(size=3, shape=16, alpha=1) +
  geom_errorbar(aes(ymin=Ave_pH - Std_pH, ymax=Ave_pH + Std_pH), width=.05)+
  geom_line(size=1)+
  # scale_color_brewer(palette='Set1') +
  ylab("pH \n") +
  xlab("\n added [H+] mM") +
  scale_y_continuous(breaks = seq(0,12,1), limits=c(0, 12))+
  ggtitle("Acidic Soil pH perturbation (Allandale: pH 4) \n") +
  # label
  # geom_text(aes(label = pH_colorimetric), size = 3, vjust = -1.5, family="serif", show.legend  = FALSE)+
  mytheme_2d


```




Visualize in grid view
```{r}
# Time points in grid
ggplot(df_pH_ave, aes(x=H_mM, y=Ave_pH, color=Soil, group=Soil)) +
  geom_point(size=3, shape=16, alpha=1) +
  geom_errorbar(aes(ymin=Ave_pH - Std_pH, ymax=Ave_pH + Std_pH), width=.05)+
  geom_line(size=1)+
  # scale_color_brewer(palette='Set1') +
  ylab("pH \n") +
  xlab("\n added [H+] mM") +
  scale_y_continuous(breaks = seq(0,12,1), limits=c(0, 12))+
  ggtitle("[n Days] Soil pH perturbation (Anaerobic incubation) \n") +
  # label
  # geom_text(aes(label = pH_colorimetric), size = 3, vjust = -1.5, family="serif", show.legend  = FALSE)+
  mytheme_2d +
  facet_wrap(Time_days ~ . , nrow=2) +
  theme(strip.background = element_rect(colour="black", fill="white", size=0.1))


# Time: hours
# Time points in grid
ggplot(df_pH_ave, aes(x=H_mM, y=Ave_pH, color=Soil, group=Soil)) +
  geom_point(size=3, shape=16, alpha=1) +
  geom_errorbar(aes(ymin=Ave_pH - Std_pH, ymax=Ave_pH + Std_pH), width=.05)+
  geom_line(size=1)+
  # scale_color_brewer(palette='Set1') +
  ylab("pH \n") +
  xlab("\n added [H+] mM") +
  scale_y_continuous(breaks = seq(0,12,1), limits=c(0, 12))+
  ggtitle("[Hours] Soil pH perturbation (Anaerobic incubation) \n") +
  # label
  # geom_text(aes(label = pH_colorimetric), size = 3, vjust = -1.5, family="serif", show.legend  = FALSE)+
  mytheme_2d +
  facet_wrap(Time_hours ~ . , nrow=2) +
  theme(strip.background = element_rect(colour="black", fill="white", size=0.1))


```



