---
title: "220418_Ammonium_standard_known_concentration"
author: "KiseokUchicago"
date: "2022-04-18"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r global_options, include=FALSE}
library(knitr)
knitr::opts_chunk$set(fig.width=11, fig.height=9,
                      error=TRUE, echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE,
                      tidy.opts=list(width.cutoff=40),tidy=TRUE)
```

## 220418 Ammonium standard re and test known concentrations
Researcher: **Kiseok Lee** \
Experiment Date: 4/18/22 \
Analysis Date: 4/18/22
Lab: **Seppe Kuehn**

```{r, include=FALSE}
# libraries
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(vegan)
library(tidyverse)
library(magrittr)
library(readxl)
library(reshape2)
library(gtools)
library(devtools)
library(openxlsx)
library(ape)
library(stringr)
library(tidyr)
library(ggrepel)
library(ggpubr)

## theme for ggplot
mytheme <- theme_bw() + 
  theme(text = element_text(family="serif")) +
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=10, family="serif"))+
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank(),panel.background=element_blank(),panel.border=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))

mytheme_2d <- theme_bw() + 
  theme(text = element_text(family="serif")) +
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=13, family="serif"))+
  theme(axis.ticks = element_line(size = 1.1))
  # theme(panel.grid.major = element_blank()) +
  # theme(panel.grid.minor = element_blank(),panel.background=element_blank(),plot.background=element_blank()) +
  


# color collection
my_color_collection <- c(
  "#CBD588", "#5F7FC7", "orange", "#AD6F3B", "#673770", 
  "#D14285", "#652926", "#C84248", "#8569D5", "#5E738F",
  "#D1A33D", "#8A7C64", "#599861","#616163", "#FFCDB2",
  "#6D9F71", "#242F40",
  "#CCA43B", "#F92A82", "#ED7B84", "#7EB77F", 
  "#DEC4A1", "#E5D1D0", '#0E8482', '#C9DAEA', '#337357', 
  '#95C623', '#E55812', '#04471C', '#F2D7EE', '#D3BCC0', 
  '#A5668B', '#69306D', '#0E103D', '#1A535C', '#4ECDC4', 
  '#F7FFF7', '#FF6B6B', '#FFE66D', '#6699CC', '#FFF275', 
  '#FF8C42', '#FF3C38', '#A23E48', '#000000', '#CF5C36', 
  '#EEE5E9', '#7C7C7C', '#EFC88B', '#2E5266', '#6E8898', 
  '#9FB1BC', '#D3D0CB', '#E2C044', '#5BC0EB', '#FDE74C', 
  '#9BC53D', '#E55934', '#FA7921', "#CD9BCD", "#508578", "#DA5724")

# for git push, use this instead of using wflow_git_push()
# git push -u origin master (in the Git app / in the working directory)

# for making pdf file
library(rmarkdown)
# render("analysis/~~.Rmd", "pdf_document")
```

## 1. Ammonium samples with known concentrationo
2mM diluted samples.

```{r}
df_known <- read.xlsx("data/220418_Ammonia_sample_plate0.xlsx")
head(df_known)

# converting ppm to mM
df_known %<>% mutate(NH4_M = Ammonia_ppm / (14.0067*1000))   # Nitrogen molecular weight 
df_known %<>% mutate(NH4_mM = NH4_M * 1000)   # Nitrogen molecular weight 
head(df_known)

# did I make a mistake of not diluting 2mM? -> changed the metadata again...
# I need to do this one more time.

df_known


ggplot(df_known, aes(x=NH4_mM, y=Ammonium_mM)) +
  geom_point(size=4, shape=21, color = "brown") +
  # geom_line(size=1)+
  # geom_errorbar(aes(ymin=NO3_mM - sd_NO3_mM, ymax=NO3_mM + sd_NO3_mM), width=.05)+
  # scale_color_brewer(palette='Set2') +
  # scale_color_manual(values = c("maroon2","deepskyblue4"))+
  ylab("Measured NH4+ concentration (mM) \n") +
  xlab("\n Known NH4+ concentration (mM)") +
  # scale_x_continuous(breaks = seq(0,16,1), limits=c(0, 16))+
  #scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  # geom_text_repel(aes(label = round(NO3_mM,3)), size = 3,family="serif", show.legend = FALSE)+
  ggtitle("Measuring known NH4+ concentration \n") +
  geom_abline(slope = 1, intercept=0)+
  mytheme_2d






```



