---
title: "220508_TOC_time_series"
author: "KiseokUchicago"
date: "2022-05-11"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=11, fig.height=9,
                      error=TRUE, echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE)
```

## TOC(Total organic carbon) measurements
Researcher: **Kiseok Lee** \
Experiment Date: 5/8/22 \
Analysis Date: 5/11/22 \
Lab: **Seppe Kuehn**

```{r}
# libraries
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(vegan)
library(tidyverse)
library(magrittr)
library(readxl)
library(reshape2)
library(gtools)
library(devtools)
library(openxlsx)
library(ape)
library(stringr)
library(tidyr)
library(ggrepel)
library(ggpubr)

## theme for ggplot
mytheme <- theme_bw() + 
  theme(text = element_text(face="bold", colour = 'black')) +
  theme(plot.title = element_text(size = 19,hjust = 0.5,face="bold", colour = 'black')) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5,face="bold", colour = 'black')) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5,face="bold", colour = 'black')) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13,face="bold", colour = 'black'))+
  theme(axis.text.y = element_text(size=13,face="bold", colour = 'black'))+
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank(),panel.background=element_blank(),panel.border=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))+
  theme(legend.text=element_text(size=10,face="bold", colour = 'black'))


mytheme_2d <- theme_bw() + 
  theme(text = element_text(face="bold", colour = 'black')) +
  theme(plot.title = element_text(size = 19,hjust = 0.5,face="bold", colour = 'black')) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5,face="bold", colour = 'black')) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5,face="bold", colour = 'black')) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13,face="bold", colour = 'black'))+
  theme(axis.text.y = element_text(size=13,face="bold", colour = 'black'))+
  # theme(panel.grid.major = element_blank()) +
  # theme(panel.grid.minor = element_blank(),panel.background=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))+
  theme(legend.text=element_text(size=10,face="bold", colour = 'black'))



# color collection
my_color_collection <- c(
  "#CBD588", "#5F7FC7", "orange", "#AD6F3B", "#673770", 
  "#D14285", "#652926", "#C84248", "#8569D5", "#5E738F",
  "#D1A33D", "#8A7C64", "#599861","#616163", "#FFCDB2",
  "#6D9F71", "#242F40",
  "#CCA43B", "#F92A82", "#ED7B84", "#7EB77F", 
  "#DEC4A1", "#E5D1D0", '#0E8482', '#C9DAEA', '#337357', 
  '#95C623', '#E55812', '#04471C', '#F2D7EE', '#D3BCC0', 
  '#A5668B', '#69306D', '#0E103D', '#1A535C', '#4ECDC4', 
  '#F7FFF7', '#FF6B6B', '#FFE66D', '#6699CC', '#FFF275', 
  '#FF8C42', '#FF3C38', '#A23E48', '#000000', '#CF5C36', 
  '#EEE5E9', '#7C7C7C', '#EFC88B', '#2E5266', '#6E8898', 
  '#9FB1BC', '#D3D0CB', '#E2C044', '#5BC0EB', '#FDE74C', 
  '#9BC53D', '#E55934', '#FA7921', "#CD9BCD", "#508578", "#DA5724")

# for git push, use this instead of using wflow_git_push()
# git push -u origin master (in the Git app / in the working directory)

# for making pdf file
library(rmarkdown)
# render("analysis/~~.Rmd", "pdf_document")

```

## 1. Import data table from python code
```{r}
# import file
# 10ul
df_20ul <- openxlsx::read.xlsx("data/220508_TOC_sample_plate1.xlsx")
df_C_T8 <- openxlsx::read.xlsx("data/220513_TOC_sample_plate1.xlsx")
df_C_T8 <- df_C_T8 %>% filter(Time_point == "C_T8") %>% select(-Antibiotics_type, -Treatment)

head(df_20ul)
colnames(df_20ul)
dim(df_20ul)

colnames(df_C_T8)
dim(df_C_T8)

# remove wells H06, H09
df_C_T8 %<>% filter(!(Well %in% c("A10","F08","F09","F10", "E10","E11")))


# remove NA
dim(df_20ul)
df_20ul <- na.omit(df_20ul)
dim(df_20ul)

dim(df_C_T8)
df_C_T8 <- na.omit(df_C_T8)
dim(df_C_T8)

# merge two
df_20ul <- rbind(df_20ul, df_C_T8)
dim(df_20ul)

# dim(df_p)
# Get the metadata for time point and left join
Time_table <- openxlsx::read.xlsx("data/220327_time_table.xlsx")
# Time_table_BN <- openxlsx::read.xlsx("data/220327_time_table_BN.xlsx")
# Time_table <- rbind(Time_table_AU, Time_table_BN)

Time_table %<>% select(-Date) 
Time_table$Time_hours <- round(Time_table$Time_hours, 1)
Time_table$Time_days <- round(Time_table$Time_days, 1)
df_time <- Time_table
dim(df_20ul)
df_20ul <- df_20ul %>% left_join(Time_table, by=("Time_point"="Time_point"))
dim(df_20ul)
colnames(df_20ul)

# get F11
df_20ul %>% filter(Well == "F11")
```

## 2. Preprocess data and select datapoints to visualize
```{r}
# 1. multiply dilution factor
df_20ul %<>% mutate(TOC_mgml = TOC_mgml * (5/2))
df_20ul %>% filter(Well == "F11")

# 2. Apply moisture correction factor (correcting for moisture in soil)
Added_Volume <- 1.7 # ml
Soil_mg <- 0.85
moisture_percent_1 = 63.1 # Webster
Added_Volume + Soil_mg*(moisture_percent_1/100)
moisture_percent_2 = 6.8 # WarrenWoods1
Added_Volume + Soil_mg*(moisture_percent_2/100)
moisture_percent_3 = 9.0 # Crerar7
Added_Volume + Soil_mg*(moisture_percent_3/100)

## acid/base
df_20ul$Added_ul <- ifelse(df_20ul$Titration_type == "NaOH", -1*df_20ul$Added_ul, df_20ul$Added_ul) # HCl is +, NaOH is -
df_20ul %<>% mutate(H_mol = Concentration_M * Added_ul * 10^(-6)) # Calculate H mol 
df_20ul$Volume <- ifelse(df_20ul$Soil == "Webster_pH3.3", Added_Volume + Soil_mg*(moisture_percent_1/100),
                      ifelse(df_20ul$Soil == "WarrenWoods1_pH5.23", Added_Volume + Soil_mg*(moisture_percent_2/100),
                             ifelse(df_20ul$Soil == "Crerar7_pH8.05", Added_Volume + Soil_mg*(moisture_percent_3/100),
                                    0))) # Calc total volume

# df_20ul$Volume <- ifelse(df_20ul$Soil == "Allandale_pH4", Added_Volume + Soil_mg*(moisture_percent_2/100), df_20ul$Volume) # Calc total volume
# df_20ul$Volume %>% unique()
df_20ul %<>% mutate(H_Molarity = H_mol / (Volume * 10^(-3)))
df_20ul %<>% mutate(H_mM = H_Molarity * 1000)
# openxlsx::write.xlsx(df_20ul, "df_20ul.xlsx")

# how many levels of H_mM?
df_20ul %>% filter(Soil == "Webster_pH3.3")%>% select(H_mM) %>% unique() %>% arrange(H_mM)
df_20ul %>% filter(Soil == "WarrenWoods1_pH5.23")%>% select(H_mM) %>% unique() %>% arrange()
df_20ul %>% filter(Soil == "Crerar7_pH8.05")%>% select(H_mM) %>% unique() %>% arrange()
colnames(df_20ul)

## Moisture correction
dim(df_20ul)

# Testing negative samples
df_no3_blank <- df_20ul %>% filter(Sample_type == "Nitrate_Blank")  # Use Nitrate_Blank instead in the future
df_no3_blank # 33

df_no2_blank <- df_20ul %>% filter(Sample_type == "Nitrite_Blank")
df_no2_blank # 33


soil_spike_ratio = 0.5 # soil weight(0.85g) / spike in volume (1.7ml) 

mcf_1 = (soil_spike_ratio*(moisture_percent_1/100) + 1)
mcf_1
mcf_2 = (soil_spike_ratio*(moisture_percent_2/100) + 1)
mcf_2
mcf_3 = (soil_spike_ratio*(moisture_percent_3/100) + 1)
mcf_3

# this is a special case with no replicates
df_20ul_mcf_1 <- df_20ul %>% filter(Soil == "Webster_pH3.3") %>% filter(Titration_type %in% c("NaOH","HCl","No_Nitrate")) %>% mutate(TOC_mgml = TOC_mgml * mcf_1)
dim(df_20ul_mcf_1) #306
df_20ul_mcf_2 <- df_20ul %>% filter(Soil == "WarrenWoods1_pH5.23") %>%  filter(Titration_type %in% c("NaOH","HCl","No_Nitrate")) %>% mutate(TOC_mgml = TOC_mgml * mcf_2)
dim(df_20ul_mcf_2) #429
df_20ul_mcf_3 <- df_20ul %>% filter(Soil == "Crerar7_pH8.05") %>% filter(Titration_type %in% c("NaOH","HCl","No_Nitrate")) %>% mutate(TOC_mgml = TOC_mgml * mcf_3)
dim(df_20ul_mcf_3) #426

df_20ul_others_mcf <- df_20ul %>% filter(Sample_type %in% c("Nitrite_Blank", "Nitrate_Blank", "Ammonium_Blank")) # Use Nitrate_Blank instead in the future
dim(df_20ul_others_mcf) #287
df_20ul_mcf <- rbind(df_20ul_mcf_1, df_20ul_mcf_2, df_20ul_mcf_3, df_20ul_others_mcf)
dim(df_20ul_mcf) # 96

df_20ul_mcf %>% filter(Well == "F11")
# 3. Calculate soil TOC percent
# soil_weight_g = 0.85
# spike_in_volume_ml = 1.7
# df_20ul_mcf %<>% mutate(TOC_percent = TOC_mgml * 0.001 * (spike_in_volume_ml / soil_weight_g) *100) 
# df_percent <- df_20ul_mcf
# colnames(df_percent)


# average technical replicate
# 
# df_ave <- df_percent %>% group_by(Sample, TOC, Sample_type) %>% summarise(Ave_TOC_percent = mean(TOC_percent), Std_TOC_percent = sd(TOC_percent), Ave_TOC_mgml = mean(TOC_mgml), Std_TOC_mgml = sd(TOC_mgml)) %>% ungroup()
# 
# colnames(df_ave)
```

## 3. Get the concentrations

```{r}
# (1) Water soluble organic C mg/ml
ggplot(df_20ul_mcf, aes(x=Time_hours, y=TOC_mgml)) +
  geom_point(size=2.5, shape=21, color = "brown") +
  geom_line(size=1, color='brown')+
  # geom_errorbar(aes(ymin=Ave_TOC_mgml - Std_TOC_mgml, ymax=Ave_TOC_mgml + Std_TOC_mgml), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("Water Soluble Organic Carbon (C mg/ml) \n") +
  xlab("\n Time (hr)") +
  # scale_x_continuous(breaks = seq(0,16,1), limits=c(0, 16))+
  #scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  ggtitle("[Before evaporation correction] Water-soluble organic carbon dynamics of no acid/base samples (3 replicates) \n") +
  # label
  # geom_text(aes(label = round(Ave_TOC_mgml,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

# plot blanks


# (2) plot separately only the H_mM  == 0 samples
df_20ul_mcf_null <- df_20ul_mcf %>% filter(H_mM  == 0, Sample_type == "Slurry")

ggplot(df_20ul_mcf_null, aes(x=Time_hours, y=TOC_mgml)) +
  geom_point(size=3, shape=16, color = "brown") +
  # geom_line(size=1, color='brown')+
  # geom_errorbar(aes(ymin=Ave_TOC_mgml - Std_TOC_mgml, ymax=Ave_TOC_mgml + Std_TOC_mgml), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("Water Soluble Organic Carbon (C mg/ml) \n") +
  xlab("\n Time (hr)") +
  scale_y_continuous(breaks = seq(0,1.5,0.1), limits=c(0, 1.5))+
  ggtitle("[Before evaporation correction] Water-soluble organic carbon dynamics of no acid/base samples (3 replicates) \n") +
  # label
  # geom_text(aes(label = round(Ave_TOC_mgml,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

# (3) plot no nitrate samples
df_20ul_mcf_nn <- df_20ul_mcf %>% filter(H_mM  == 0, Titration_type == "No_Nitrate")
# df_20ul_mcf$Titration_type

ggplot(df_20ul_mcf_nn, aes(x=Time_hours, y=TOC_mgml)) +
  geom_point(size=3, shape=16, color = "brown") +
  # geom_line(size=1, color='brown')+
  # geom_errorbar(aes(ymin=Ave_TOC_mgml - Std_TOC_mgml, ymax=Ave_TOC_mgml + Std_TOC_mgml), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("Water Soluble Organic Carbon (C mg/ml) \n") +
  xlab("\n Time (hr)") +
  # scale_y_continuous(breaks = seq(0,1.5,0.1), limits=c(0, 1.5))+
  ggtitle("[Before evaporation correction] Water-soluble organic carbon dynamics of no NO3- samples (3 replicates) \n") +
  # label
  # geom_text(aes(label = round(Ave_TOC_mgml,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

# what is happening with no nitrate sample?
df_20ul_mcf_nn


```

Correcting for evaporation
```{r}
# for Crerar7 NO2, correction factor for T10 is 
# 0.9825210

0.983/1.05 # NO2
0.973/0.999 # NO3

# for T8
1.0384184/1.05 # NO2
1.0316592/0.999 # NO3

# let's use NO2's evaporation factor
eva_correction_factor = 0.983/1.05
df_20ul_mcf_bcf_1 <- df_20ul_mcf %>% filter(Time_point == "C_T10") %>% mutate(TOC_mgml = TOC_mgml * eva_correction_factor)
eva_correction_factor = 1.0384184/1.05
df_20ul_mcf_bcf_2 <- df_20ul_mcf %>% filter(Time_point == "C_T8") %>% mutate(TOC_mgml = TOC_mgml * eva_correction_factor)

df_20ul_mcf_bcf_others <- df_20ul_mcf %>% filter(Time_point == "C_T0")
df_20ul_mcf_bcf <- rbind(df_20ul_mcf_bcf_1, df_20ul_mcf_bcf_2, df_20ul_mcf_bcf_others)
dim(df_20ul_mcf_bcf)

# Redo the plots
# (1) Water soluble organic C mg/ml
ggplot(df_20ul_mcf_bcf, aes(x=Time_hours, y=TOC_mgml)) +
  geom_point(size=2.5, shape=21, color = "brown") +
  geom_line(size=1, color='brown')+
  # geom_errorbar(aes(ymin=Ave_TOC_mgml - Std_TOC_mgml, ymax=Ave_TOC_mgml + Std_TOC_mgml), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("Water Soluble Organic Carbon (C mg/ml) \n") +
  xlab("\n Time (hr)") +
  # scale_x_continuous(breaks = seq(0,16,1), limits=c(0, 16))+
  #scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  ggtitle("[After evaporation correction] Water-soluble organic carbon dynamics of no acid/base samples (3 replicates) \n") +
  # label
  # geom_text(aes(label = round(Ave_TOC_mgml,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

# (2) plot separately only the H_mM  == 0 samples
df_20ul_mcf_bcf_null <- df_20ul_mcf_bcf %>% filter(H_mM  == 0, Sample_type == "Slurry")

ggplot(df_20ul_mcf_bcf_null, aes(x=Time_hours, y=TOC_mgml)) +
  geom_point(size=3, shape=16, color = "brown") +
  # geom_line(size=1, color='brown')+
  # geom_errorbar(aes(ymin=Ave_TOC_mgml - Std_TOC_mgml, ymax=Ave_TOC_mgml + Std_TOC_mgml), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("Water Soluble Organic Carbon (C mg/ml) \n") +
  xlab("\n Time (hr)") +
  scale_y_continuous(breaks = seq(0,1.5,0.1), limits=c(0, 1.5))+
  ggtitle("[After evaporation correction] Water-soluble organic carbon dynamics of no acid/base samples (3 replicates) \n") +
  # label
  # geom_text(aes(label = round(Ave_TOC_mgml,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

# (3) plot no nitrate samples
df_20ul_mcf_bcf_nn <- df_20ul_mcf_bcf %>% filter(H_mM  == 0, Titration_type == "No_Nitrate")
# df_20ul_mcf$Titration_type

ggplot(df_20ul_mcf_bcf_nn, aes(x=Time_hours, y=TOC_mgml)) +
  geom_point(size=3, shape=16, color = "brown") +
  # geom_line(size=1, color='brown')+
  # geom_errorbar(aes(ymin=Ave_TOC_mgml - Std_TOC_mgml, ymax=Ave_TOC_mgml + Std_TOC_mgml), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("Water Soluble Organic Carbon (C mg/ml) \n") +
  xlab("\n Time (hr)") +
  scale_y_continuous(breaks = seq(0,2,0.1), limits=c(0, 2))+
  ggtitle("[After evaporation correction] Water-soluble organic carbon dynamics of no NO3- samples (3 replicates) \n") +
  # label
  # geom_text(aes(label = round(Ave_TOC_mgml,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

# (4) plot blanks
df_20ul_mcf_bcf_blk <- df_20ul_mcf_bcf %>% filter(Sample_type %in% c("Nitrite_Blank", "Nitrate_Blank", "Ammonium_Blank"))
# df_20ul_mcf$Titration_type

ggplot(df_20ul_mcf_bcf_blk, aes(x=Time_hours, y=TOC_mgml)) +
  geom_point(size=3, shape=16, aes(color = Sample_type)) +
  # geom_line(size=1, color='brown')+
  # geom_errorbar(aes(ymin=Ave_TOC_mgml - Std_TOC_mgml, ymax=Ave_TOC_mgml + Std_TOC_mgml), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("Water Soluble Organic Carbon (C mg/ml) \n") +
  xlab("\n Time (hr)") +
  scale_y_continuous(breaks = seq(0,1.5,0.1), limits=c(0, 1.5))+
  ggtitle("[After evaporation correction] Water-soluble organic carbon dynamics of blanks (3 replicates) \n") +
  # label
  # geom_text(aes(label = round(Ave_TOC_mgml,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

df_20ul_mcf_bcf_blk %>% filter(Sample_type == "Nitrite_Blank")

df_20ul_mcf_bcf_blk %>% filter(Sample_type == "Nitrate_Blank")

df_20ul_mcf_bcf_blk %>% filter(Sample_type == "Ammonium_Blank")


```


Plot by coloring it
```{r}
# pH color
col_pH <- colorRampPalette(c("gold","red","purple"))

library(colorRamps)
colorRamps::green2red
plot(rep(1,13),col=col_pH(13),pch=19,cex=3)
grad_pH <- scale_colour_gradientn(colours = col_pH(100))

# Confer this page (https://stackoverflow.com/questions/21537782/how-to-set-fixed-continuous-colour-values-in-ggplot2)
# myPalette <- colorRampPalette(rev(brewer.pal(11, "Spectral")))
# sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(1, 8))

# 1. pH perturbation
# plot Ammonia
df_20ul_mcf <- df_20ul_mcf %>% filter(Titration_type %in% c("NaOH","HCl"))

dim(df_20ul_mcf)
colnames(df_20ul_mcf)

# average the no acid base one.
df_plot <- df_20ul_mcf %>% select(H_mM, TOC_mgml, Soil, Time_hours)
df_plot %>% filter(H_mM == 0) %>% dim()
df_plot %>% filter(H_mM == 0) %>% group_by(H_mM, Soil, Time_hours) %>% summarize(TOC_mgml = mean(TOC_mgml)) %>% ungroup()
df_sub <- df_plot %>% filter(H_mM == 0) %>% group_by(H_mM, Soil, Time_hours) %>% summarize(TOC_mgml = mean(TOC_mgml)) %>% ungroup()
df_main <- df_plot %>% filter(H_mM != 0)
dim(df_plot)
dim(df_main)
df_plot2 <- rbind(df_main, df_sub)
dim(df_plot2)

#export to plot with nitrate, nitrite
# write.xlsx(df_plot2, "220420-2_Ammonia_bcf.xlsx")

ggplot(df_plot2, aes(x=Time_hours, y=TOC_mgml, color=H_mM, group=H_mM)) +
  geom_point(size=2.5, shape=16) +
  geom_line(size=1.2)+
  # geom_errorbar(aes(ymin=NH4_mM - Std_NH4_mM, ymax=NH4_mM + Std_NH4_mM), width=.05)+
  scale_colour_gradientn(colours = col_pH(100)) +
  # scale_color_manual(values=grad_pH) +
  ylab("Water Soluble Organic Carbon (C mg/ml) \n") +
  xlab("\n Time (hr)") +
  # scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  ggtitle("[Before evaporation correction] Water-soluble organic carbon dynamics \n") +
  # label
  # geom_text(aes(label = round(NH4_mM,3)), size = 3, vjust = -1.5, face="bold", show.legend = FALSE)+
  mytheme_2d +
  facet_grid(. ~ Soil) +
  theme(strip.background = element_rect(colour="black", fill="white", size=0.1))+
  theme(strip.text.x = element_text(size = 17))

```

Evaporation correction

```{r}
# average the no acid base one.
df_20ul_mcf_bcf %>% filter(Titration_type %in% c("NaOH", "HCl"))
df_plot <- df_20ul_mcf_bcf %>% filter(Titration_type %in% c("NaOH", "HCl")) %>% select(H_mM, TOC_mgml, Soil, Time_hours)
df_plot %>% filter(H_mM == 0) %>% dim()
df_plot %>% filter(H_mM == 0) %>% group_by(H_mM, Soil, Time_hours) %>% summarize(TOC_mgml = mean(TOC_mgml)) %>% ungroup()
df_sub <- df_plot %>% filter(H_mM == 0) %>% group_by(H_mM, Soil, Time_hours) %>% summarize(TOC_mgml = mean(TOC_mgml)) %>% ungroup()
df_main <- df_plot %>% filter(H_mM != 0)
dim(df_plot)
dim(df_main)
df_plot2 <- rbind(df_main, df_sub)
dim(df_plot2)

# export to plot with nitrate, nitrite
# write.xlsx(df_plot2, "220420-2_Ammonia_bcf.xlsx")

ggplot(df_plot2, aes(x=Time_hours, y=TOC_mgml, color=H_mM, group=H_mM)) +
  geom_point(size=2.5, shape=16) +
  geom_line(size=1.2)+
  # geom_errorbar(aes(ymin=NH4_mM - Std_NH4_mM, ymax=NH4_mM + Std_NH4_mM), width=.05)+
  scale_colour_gradientn(colours = col_pH(100)) +
  # scale_color_manual(values=grad_pH) +
  ylab("Water Soluble Organic Carbon (C mg/ml) \n") +
  xlab("\n Time (hr)") +
  scale_y_continuous(breaks = seq(0,1.5,0.5), limits=c(0, 1.5))+
  ggtitle("[After evaporation correction] Water-soluble organic carbon dynamics \n") +
  # label
  # geom_text(aes(label = round(NH4_mM,3)), size = 3, vjust = -1.5, face="bold", show.legend = FALSE)+
  mytheme_2d +
  facet_grid(. ~ Soil) +
  theme(strip.background = element_rect(colour="black", fill="white", size=0.1))+
  theme(strip.text.x = element_text(size = 17))

# plot by treatment (titration type)
df_plot3 <- df_plot2
df_plot3$Titration_type <- ifelse(df_plot3$H_mM > 40, "Acidic perturbation",
                                  ifelse(df_plot3$H_mM < -40, "Basic perturbation",
                                         "Neutral range"))

ggplot(df_plot3, aes(x=Time_hours, y=TOC_mgml, color=H_mM, group=H_mM)) +
  geom_point(size=2.5, shape=16) +
  geom_line(size=1.2)+
  # geom_errorbar(aes(ymin=NH4_mM - Std_NH4_mM, ymax=NH4_mM + Std_NH4_mM), width=.05)+
  scale_colour_gradientn(colours = col_pH(100)) +
  # scale_color_manual(values=grad_pH) +
  ylab("Water Soluble Organic Carbon (C mg/ml) \n") +
  xlab("\n Time (hr)") +
  scale_y_continuous(breaks = seq(0,1.5,0.5), limits=c(0, 1.5))+
  ggtitle("[After evaporation correction] Water-soluble organic carbon dynamics \n") +
  # label
  # geom_text(aes(label = round(NH4_mM,3)), size = 3, vjust = -1.5, face="bold", show.legend = FALSE)+
  mytheme_2d +
  facet_grid(. ~ Titration_type) +
  theme(strip.background = element_rect(colour="black", fill="white", size=0.1))+
  theme(strip.text.x = element_text(size = 17))



## plot the
ggplot(df_plot2, aes(x=H_mM, y=TOC_mgml, color=H_mM, group=H_mM)) +
  geom_point(size=2.5, shape=16) +
  geom_line(size=1.2)+
  # geom_errorbar(aes(ymin=NH4_mM - Std_NH4_mM, ymax=NH4_mM + Std_NH4_mM), width=.05)+
  scale_colour_gradientn(colours = col_pH(100)) +
  # scale_color_manual(values=grad_pH) +
  ylab("Water Soluble Organic Carbon (C mg/ml) \n") +
  xlab("\n H+ (mM)") +
  scale_y_continuous(breaks = seq(0,1.5,0.5), limits=c(0, 1.5))+
  ggtitle("[After evaporation correction] Water-soluble organic carbon at beginning and endpoint \n") +
  # label
  # geom_text(aes(label = round(NH4_mM,3)), size = 3, vjust = -1.5, face="bold", show.legend = FALSE)+
  mytheme_2d +
  facet_grid(. ~ Time_hours) +
  theme(strip.background = element_rect(colour="black", fill="white", size=0.1))+
  theme(strip.text.x = element_text(size = 17))


```


