---
title: "220527_TOC_biomass_microwave_ecoli2_30s_45s"
author: "KiseokUchicago"
date: "2022-05-28"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=11, fig.height=9,
                      error=TRUE, echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE)
```

## TOC(Total organic carbon) measurements: Biomass measurement
Researcher: **Kiseok Lee** \
Experiment Date: 5/27/22 \
Analysis Date: 5/28/22 \
Lab: **Seppe Kuehn**

```{r}
# libraries
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(vegan)
library(tidyverse)
library(magrittr)
library(readxl)
library(reshape2)
library(gtools)
library(devtools)
library(openxlsx)
library(ape)
library(stringr)
library(tidyr)
library(ggrepel)
library(ggpubr)

## theme for ggplot
mytheme <- theme_bw() + 
  theme(text = element_text(face="bold", colour = 'black')) +
  theme(plot.title = element_text(size = 19,hjust = 0.5,face="bold", colour = 'black')) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5,face="bold", colour = 'black')) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5,face="bold", colour = 'black')) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13,face="bold", colour = 'black'))+
  theme(axis.text.y = element_text(size=13,face="bold", colour = 'black'))+
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank(),panel.background=element_blank(),panel.border=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))+
  theme(legend.text=element_text(size=10,face="bold", colour = 'black'))


mytheme_2d <- theme_bw() + 
  theme(text = element_text(face="bold", colour = 'black')) +
  theme(plot.title = element_text(size = 19,hjust = 0.5,face="bold", colour = 'black')) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5,face="bold", colour = 'black')) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5,face="bold", colour = 'black')) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13,face="bold", colour = 'black'))+
  theme(axis.text.y = element_text(size=13,face="bold", colour = 'black'))+
  # theme(panel.grid.major = element_blank()) +
  # theme(panel.grid.minor = element_blank(),panel.background=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))+
  theme(legend.text=element_text(size=10,face="bold", colour = 'black'))



# color collection
my_color_collection <- c(
  "#CBD588", "#5F7FC7", "orange", "#AD6F3B", "#673770", 
  "#D14285", "#652926", "#C84248", "#8569D5", "#5E738F",
  "#D1A33D", "#8A7C64", "#599861","#616163", "#FFCDB2",
  "#6D9F71", "#242F40",
  "#CCA43B", "#F92A82", "#ED7B84", "#7EB77F", 
  "#DEC4A1", "#E5D1D0", '#0E8482', '#C9DAEA', '#337357', 
  '#95C623', '#E55812', '#04471C', '#F2D7EE', '#D3BCC0', 
  '#A5668B', '#69306D', '#0E103D', '#1A535C', '#4ECDC4', 
  '#F7FFF7', '#FF6B6B', '#FFE66D', '#6699CC', '#FFF275', 
  '#FF8C42', '#FF3C38', '#A23E48', '#000000', '#CF5C36', 
  '#EEE5E9', '#7C7C7C', '#EFC88B', '#2E5266', '#6E8898', 
  '#9FB1BC', '#D3D0CB', '#E2C044', '#5BC0EB', '#FDE74C', 
  '#9BC53D', '#E55934', '#FA7921', "#CD9BCD", "#508578", "#DA5724")

# for git push, use this instead of using wflow_git_push()
# git push -u origin master (in the Git app / in the working directory)

# for making pdf file
library(rmarkdown)
# render("analysis/~~.Rmd", "pdf_document")

```

## 1. Import data table from python code
```{r}
# import file
# 20ul
df_20ul_1 <- openxlsx::read.xlsx("data/220527_TOC_sample_plate1.xlsx")
# df_20ul_2 <- openxlsx::read.xlsx("data/220527_TOC_sample_plate2.xlsx")
# df_20ul_3 <- openxlsx::read.xlsx("data/220527_TOC_sample_plate3.xlsx")

# only use left six columns
# df_20ul_1 %<>% filter(Soil == "LaBaghWoods_pH6.66")

# remove wells H06, H09
# df_20ul_1 %<>% filter(!(Well %in% c("A01", "A03", "H03")))
# dim(df_20ul_1)
# df_20ul_2 %<>% filter(!(Well %in% c("D12")))
# dim(df_20ul_3)

# head(df_20ul_2)
# colnames(df_20ul_2)
# dim(df_20ul_2)

df_20ul <- rbind(df_20ul_1)

# remove NA
dim(df_20ul)
df_20ul <- na.omit(df_20ul)
dim(df_20ul)


# Get the metadata for time point and left join
# Time_table <- openxlsx::read.xlsx("data/220519_time_table.xlsx")
# Time_table_BN <- openxlsx::read.xlsx("data/220327_time_table_BN.xlsx")
# Time_table <- rbind(Time_table_AU, Time_table_BN)

# Time_table %<>% select(-Date) 
# Time_table$Time_hours <- round(Time_table$Time_hours, 1)
# Time_table$Time_days <- round(Time_table$Time_days, 1)
# df_time <- Time_table
# dim(df_20ul)
# df_20ul <- df_20ul %>% left_join(Time_table, by=("Time_point"="Time_point"))
# dim(df_20ul)
# colnames(df_20ul)

```


## 2. Let's plot
```{r}
colnames(df_20ul)
# look at the LB
df_plot <- df_20ul
df_plot$Microwave_sec <- factor(df_plot$Microwave_sec)

ggplot(df_plot, aes(x=Dilution_factor, y=TOC_mgml, color=Microwave_sec, group=Microwave_sec)) +
  geom_point(size=3, shape=16) +
  # geom_line(size=1.2)+
  # geom_errorbar(aes(ymin=NO3_mM - Std_NO3_mM, ymax=NO3_mM + Std_NO3_mM), width=.05)+
  # scale_colour_gradientn(colours = col_pH(100)) +
  # scale_color_manual(values=c("Black","Red","Blue", "Purple", "Brown")) +
  ylab("Carbon (mg/ml)") +
  xlab("Dilution factor (serial dilution)") +
  # scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  # ggtitle("Antibiotics application x pH perturbation (pH at day2): 200ppm of Chloramphenicol(CHL), Nystatin(NYT) \n") +
  # label
  # geom_text(aes(label = round(NO3_mM,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

ggplot(df_plot, aes(x=Dilution_factor, y=TOC_mgml, color=Microwave_sec, group=Microwave_sec)) +
  geom_point(size=3, shape=16) +
  # geom_line(size=1.2)+
  # geom_errorbar(aes(ymin=NO3_mM - Std_NO3_mM, ymax=NO3_mM + Std_NO3_mM), width=.05)+
  # scale_colour_gradientn(colours = col_pH(100)) +
  # scale_color_manual(values=c("Black","Red","Blue", "Purple", "Brown")) +
  ylab("Carbon (mg/ml)") +
  xlab("Dilution factor (serial dilution)") +
  # scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  # ggtitle("Antibiotics application x pH perturbation (pH at day2): 200ppm of Chloramphenicol(CHL), Nystatin(NYT) \n") +
  # label
  # geom_text(aes(label = round(NO3_mM,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d +
  # ggtitle("pH (Cycloheximide-treated)") +
  facet_grid(. ~ Sample_type) +
  theme(strip.background = element_rect(colour="black", fill="white", size=0.1))+
  theme(strip.text.x = element_text(size = 17))

# subtract the control
df_control <- df_plot %>% filter(Sample_type == "Control") 
df_ave_control <- df_control %>% group_by(Dilution_factor) %>% summarize(Control_mgml=mean(TOC_mgml))

# plot control
ggplot(df_control, aes(x=Dilution_factor, y=TOC_mgml)) +
  geom_point(size=3, shape=16, color = "maroon") +
  # geom_line(size=1.2)+
  # geom_errorbar(aes(ymin=NO3_mM - Std_NO3_mM, ymax=NO3_mM + Std_NO3_mM), width=.05)+
  # scale_colour_gradientn(colours = col_pH(100)) +
  # scale_color_manual(values=c("Black","Red","Blue", "Purple", "Brown")) +
  ylab("Carbon (mg/ml)") +
  xlab("Dilution factor (serial dilution)") +
  # scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  ggtitle("Control (no microwave) \n") +
  # label
  # geom_text(aes(label = round(NO3_mM,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

# plot control
ggplot(df_ave_control, aes(x=Dilution_factor, y=Control_mgml)) +
  geom_line(size=1, color = "maroon")+
  geom_point(size=3, shape=16, color = "maroon") +
  # geom_errorbar(aes(ymin=NO3_mM - Std_NO3_mM, ymax=NO3_mM + Std_NO3_mM), width=.05)+
  # scale_colour_gradientn(colours = col_pH(100)) +
  # scale_color_manual(values=c("Black","Red","Blue", "Purple", "Brown")) +
  ylab("Carbon (mg/ml)") +
  xlab("Dilution factor (serial dilution)") +
  # scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  ggtitle("Control (no microwave) \n") +
  # label
  # geom_text(aes(label = round(NO3_mM,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

# let's plot subtracting
df_subtracted <- df_plot %>% filter(Sample_type == "MW") %>% left_join(df_ave_control, by = c("Dilution_factor"="Dilution_factor")) %>% mutate(TOC_mgml = TOC_mgml - Control_mgml)
df_subtracted$Microwave_sec <- factor(df_subtracted$Microwave_sec)

# plot subtracted
ggplot(df_subtracted, aes(x=Dilution_factor, y=TOC_mgml, color = Microwave_sec)) +
  geom_point(size=3, shape=16) +
  # geom_line(size=1.2)+
  # geom_errorbar(aes(ymin=NO3_mM - Std_NO3_mM, ymax=NO3_mM + Std_NO3_mM), width=.05)+
  # scale_colour_gradientn(colours = col_pH(100)) +
  # scale_color_manual(values=c("Black","Red","Blue", "Purple", "Brown")) +
  ylab("Carbon (mg/ml)") +
  xlab("Dilution factor (serial dilution)") +
  # scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  ggtitle("MW sample - Control \n") +
  # label
  # geom_text(aes(label = round(NO3_mM,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

# plot subtract control
ggplot(df_subtracted, aes(x=Dilution_factor, y=TOC_mgml, color = Microwave_sec)) +
  geom_point(size=3, shape=16) +
  # geom_line(size=1.2)+
  # geom_errorbar(aes(ymin=NO3_mM - Std_NO3_mM, ymax=NO3_mM + Std_NO3_mM), width=.05)+
  # scale_colour_gradientn(colours = col_pH(100)) +
  # scale_color_manual(values=c("Black","Red","Blue", "Purple", "Brown")) +
  ylab("Carbon (mg/ml)") +
  xlab("Dilution factor (serial dilution)") +
  # scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  ggtitle("MW sample - Control \n") +
  # label
  # geom_text(aes(label = round(NO3_mM,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d +
  # ggtitle("pH (Cycloheximide-treated)") +
  facet_grid(. ~ Microwave_sec) +
  theme(strip.background = element_rect(colour="black", fill="white", size=0.1))+
  theme(strip.text.x = element_text(size = 17))





```



