---
title: "Blank_extraction_2MKCl_Griess_211007"
author: "KiseokUchicago"
date: "2021-10-08"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=11, fig.height=9,
                      error=TRUE, echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE)
```

## Blank extraction 2M KCl test (Griess assay)
Researcher: **Kiseok Lee** \
Experiment Date: 10/7/21 \
Analysis Date: 10/8/21
Lab: **Seppe Kuehn**

```{r}
# libraries
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(vegan)
library(tidyverse)
library(magrittr)
library(readxl)
library(reshape2)
library(gtools)
library(devtools)
library(openxlsx)
library(ape)
library(stringr)
library(tidyr)
library(ggrepel)
library(ggpubr)

## theme for ggplot
mytheme <- theme_bw() + 
  theme(text = element_text(family="serif")) +
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=10, family="serif"))+
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank(),panel.background=element_blank(),panel.border=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))

mytheme_2d <- theme_bw() + 
  theme(text = element_text(family="serif")) +
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=13, family="serif"))+
  # theme(panel.grid.major = element_blank()) +
  # theme(panel.grid.minor = element_blank(),panel.background=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))


# color collection
my_color_collection <- c(
  "#CBD588", "#5F7FC7", "orange", "#AD6F3B", "#673770", 
  "#D14285", "#652926", "#C84248", "#8569D5", "#5E738F",
  "#D1A33D", "#8A7C64", "#599861","#616163", "#FFCDB2",
  "#6D9F71", "#242F40",
  "#CCA43B", "#F92A82", "#ED7B84", "#7EB77F", 
  "#DEC4A1", "#E5D1D0", '#0E8482', '#C9DAEA', '#337357', 
  '#95C623', '#E55812', '#04471C', '#F2D7EE', '#D3BCC0', 
  '#A5668B', '#69306D', '#0E103D', '#1A535C', '#4ECDC4', 
  '#F7FFF7', '#FF6B6B', '#FFE66D', '#6699CC', '#FFF275', 
  '#FF8C42', '#FF3C38', '#A23E48', '#000000', '#CF5C36', 
  '#EEE5E9', '#7C7C7C', '#EFC88B', '#2E5266', '#6E8898', 
  '#9FB1BC', '#D3D0CB', '#E2C044', '#5BC0EB', '#FDE74C', 
  '#9BC53D', '#E55934', '#FA7921', "#CD9BCD", "#508578", "#DA5724")

# for git push, use this instead of using wflow_git_push()
# git push -u origin master (in the Git app / in the working directory)

```


## 1. Import data table from python code
```{r}
# import file
df_p1 <- openxlsx::read.xlsx("data/211007_Griess_blank_plate1.xlsx")
df_p2 <- openxlsx::read.xlsx("data/211007_Griess_blank_plate2.xlsx")

class(df_p1)
head(df_p1)
colnames(df_p1)
dim(df_p1)

class(df_p2)
head(df_p2)
colnames(df_p2)
dim(df_p2)

# bind two dataframe
df_p <- rbind(df_p1, df_p2)

colnames(df_p)
dim(df_p)

# remove NA
dim(df_p)
df_p <- na.omit(df_p)
dim(df_p)

# Check
df_p %>% filter(Well =="H06")
df_p %>% filter(Well =="H09")

# remove wells H06, H09
# df_p %<>% filter(!(Well %in% c("H06","H09")))
# dim(df_p)

```

## 2. Get average and standard deviation
```{r}
# average and standard deviation
head(df_p)
dim(df_p)

# average technical replicate
df_NO2NO3 <- df_p %>% group_by(Sample, Nitrate_input, Sample_type, Replicate, Plate) %>% summarise(Ave_NO2_mM = mean(NO2_mM), Std_NO2_mM = sd(NO2_mM), Ave_NO2NO3_mM = mean(NO2NO3_mM), Std_NO2NO3_mM = sd(NO2NO3_mM), Ave_NO3_mM = mean(NO2NO3_mM - NO2_mM), Std_NO3_mM = sd(NO2NO3_mM - NO2_mM)) %>% ungroup()

# plot to see
ggplot(df_NO2NO3, aes(x=Nitrate_input, y=Ave_NO3_mM, color=Sample_type, group=Sample_type)) +
  geom_point(size=2.5, shape=21) +
  # geom_line(size=1)+
  geom_errorbar(aes(ymin=Ave_NO3_mM - Std_NO3_mM, ymax=Ave_NO3_mM + Std_NO3_mM), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("NO3- (mM) \n") +
  xlab("\n Nitrate_spike_in (mM)") +
  # scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  ggtitle("Ploting nitrate concentration \n") +
  mytheme_2d

# average biological replicates & standard deviation is the standard deviation of the technical replicate average
dim(df_NO2NO3)
head(df_NO2NO3)

df_blank <- df_NO2NO3 %>% group_by(Nitrate_input, Sample_type, Plate) %>% summarise(NO2_mM = mean(Ave_NO2_mM), sd_NO2_mM = sd(Ave_NO2_mM), NO2NO3_mM = mean(Ave_NO2NO3_mM), sd_NO2NO3_mM = sd(Ave_NO2NO3_mM), NO3_mM = mean(Ave_NO2NO3_mM - Ave_NO2_mM), sd_NO3_mM = sd(Ave_NO2NO3_mM - Ave_NO2_mM)) %>% ungroup()

dim(df_blank)

colnames(df_blank)

# plot to see
ggplot(df_blank, aes(x=Nitrate_input, y=NO3_mM, color=Sample_type, group=Sample_type)) +
  geom_point(size=2.5, shape=21) +
  # geom_line(size=1)+
  geom_errorbar(aes(ymin=NO3_mM - sd_NO3_mM, ymax=NO3_mM + sd_NO3_mM), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("NO3- (mM) \n") +
  xlab("\n Nitrate_spike_in (mM)") +
  # scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  ggtitle("Ploting nitrate concentration \n") +
  mytheme_2d

# Factor in orders
# df_all$Sample_type <-  factor(df_all$Sample_type, levels = c("Soil","Blank"))

```

## 3. Plot

```{r}
# Plot blank (without soil) samples
df_blank

ggplot(df_blank, aes(x=Nitrate_input, y=NO3_mM, color=Sample_type, group=Sample_type)) +
  geom_point(size=2.5, shape=21) +
  # geom_line(size=1)+
  geom_errorbar(aes(ymin=NO3_mM - sd_NO3_mM, ymax=NO3_mM + sd_NO3_mM), width=.05)+
  # scale_color_brewer(palette='Set2') +
  scale_color_manual(values = c("deepskyblue4","maroon2"))+
  ylab("Measured NO3- (mM) \n") +
  xlab("\n Nitrate_spike_in (mM)") +
  # scale_y_continuous(breaks = seq(0,2.1,0.25), limits=c(0, 2))+
  # scale_x_continuous(breaks = seq(0,2.1,0.25), limits=c(0, 2))+
  ggtitle("Blank spike in \n") +
  geom_abline(slope = 1, intercept=0, show.legend = "y=x")+
  mytheme_2d

# Plot separately for H2O based spike ins
df_h2o <- df_blank %>% filter(Sample_type =="Blank_H2O")

ggplot(df_h2o, aes(x=Nitrate_input, y=NO3_mM, color=Sample_type, group=Sample_type)) +
  geom_point(size=2.5, shape=21) +
  # geom_line(size=1)+
  geom_errorbar(aes(ymin=NO3_mM - sd_NO3_mM, ymax=NO3_mM + sd_NO3_mM), width=.05)+
  # scale_color_brewer(palette='Set2') +
  scale_color_manual(values = c("deepskyblue4","maroon2"))+
  ylab("Measured NO3- (mM) \n") +
  xlab("\n Nitrate_spike_in (mM)") +
  # scale_y_continuous(breaks = seq(0,2.1,0.25), limits=c(0, 2))+
  scale_x_continuous(breaks = seq(0,2.1,0.1), limits=c(0, 2.1))+
  geom_text_repel(aes(label = round(NO3_mM,3)), size = 3,family="serif", show.legend = FALSE)+
  ggtitle("Water based Blank spike in \n") +
  geom_abline(slope = 1, intercept=0, show.legend = "y=x")+
  mytheme_2d


# Plot separately for KCl based spike ins
df_kcl <- df_blank %>% filter(Sample_type =="Blank_KCl")

ggplot(df_kcl, aes(x=Nitrate_input, y=NO3_mM, color=Sample_type, group=Sample_type)) +
  geom_point(size=2.5, shape=21) +
  # geom_line(size=1)+
  geom_errorbar(aes(ymin=NO3_mM - sd_NO3_mM, ymax=NO3_mM + sd_NO3_mM), width=.05)+
  # scale_color_brewer(palette='Set2') +
  scale_color_manual(values = c("maroon2"))+
  ylab("Measured NO3- (mM) \n") +
  xlab("\n Nitrate_spike_in (mM)") +
  # scale_y_continuous(breaks = seq(0,2.1,0.25), limits=c(0, 2))+
  scale_x_continuous(breaks = seq(0,2.1,0.1), limits=c(0, 2.1))+
  geom_text_repel(aes(label = round(NO3_mM,3)), size = 3,family="serif", show.legend = FALSE)+
  ggtitle("2M KCl based Blank spike in \n") +
  geom_abline(slope = 1, intercept=0, show.legend = "y=x")+
  mytheme_2d

# Retrieved ratio of spike ins
df_blank$Ratio_retrieved <- df_blank$NO3_mM / df_blank$Nitrate_input

df_ratio <- df_blank %>% filter(!(Nitrate_input == 0))

ggplot(df_ratio, aes(x=Nitrate_input, y=Ratio_retrieved, fill=Sample_type, group=Sample_type)) +  ## I put fill=value which was wrong
  geom_bar(stat="identity",position="dodge")+
  # geom_line(size=0.2, color="black")+
  scale_fill_manual(values = c("deepskyblue4","maroon2"))+
  ylab("Ratio of retrieved nitrate concentraion \n") +
  xlab("\n Nitrate_spike_in (mM)") +
  scale_y_continuous(breaks = seq(0,4,0.5), limits=c(0, 4))+
  scale_x_continuous(breaks = seq(0,2.1,0.1), limits=c(0, 2.1))+
  ggtitle("Retrieved nitrate ratio \n") +
  geom_text_repel(aes(label = round(Ratio_retrieved,3)), size = 3,family="serif", show.legend = FALSE)+
  mytheme_2d


```

## 4. Subtract the spike ins... are there patterns for the anomaly of blanks?

```{r}
# subtract the concentration of spike ins
df_over <- df_blank %>% mutate(Nitrate_over_spike_in_mM = NO3_mM - Nitrate_input)

ggplot(df_over, aes(x=Nitrate_input, y=Nitrate_over_spike_in_mM, color=Sample_type, group=Sample_type)) +
  geom_point(size=2.5, shape=21) +
  geom_line(size=1)+
  # scale_color_brewer(palette='Set2') +
  scale_color_manual(values = c("deepskyblue4","maroon2"))+
  ylab("Measured NO3 - Spiked in NO3 (mM) \n") +
  xlab("\n Nitrate_spike_in (mM)") +
  scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  scale_x_continuous(breaks = seq(0,2.1,0.25), limits=c(0, 2))+
  # geom_text_repel(aes(label = round(Nitrate_over_spike_in_mM,3)), size = 3,family="serif", show.legend = FALSE)+
  ggtitle("Over-measured Nitrate \n") +
  geom_abline(slope = 0, intercept=0, show.legend = "y=x")+
  mytheme_2d


```

## 5. Linear regression of raw data.
```{r}
head(df_p)
df_raw <- df_p %>% mutate(NO3_mM = NO2NO3_mM - NO2_mM)

df_raw_h2o <- df_raw %>% filter(Sample_type == "Blank_H2O")
dim(df_raw_h2o)

df_raw_kcl <- df_raw %>% filter(Sample_type == "Blank_KCl")
dim(df_raw_kcl)

fit.h2o <- lm(NO3_mM ~ Nitrate_input, df_raw_h2o)
fit.kcl <- lm(NO3_mM ~ Nitrate_input, df_raw_kcl)

# H2O based
# Plot fitted linear regression line
ggplot(df_raw_h2o, aes(x=Nitrate_input, y=NO3_mM, color=Sample_type, group=Sample_type)) +
  geom_point(size=2.5, shape=21) +
  # geom_line(size=1)+
  # geom_errorbar(aes(ymin=NO3_mM - sd_NO3_mM, ymax=NO3_mM + sd_NO3_mM), width=.05)+
  # scale_color_brewer(palette='Set2') +
  scale_color_manual(values = c("deepskyblue4","maroon2"))+
  ylab("Measured NO3- (mM) \n") +
  xlab("\n Nitrate_spike_in (mM)") +
  scale_y_continuous(breaks = seq(0,2.25,0.25), limits=c(0, 2.25))+
  scale_x_continuous(breaks = seq(0,2.1,0.1), limits=c(0, 2.1))+
  # geom_text_repel(aes(label = round(NO3_mM,3)), size = 3,family="serif", show.legend = FALSE)+
  ggtitle("Water based Blank spike in \n") +
  geom_abline(slope = 1, intercept=0, show.legend = "y=x")+
  # regression line
  geom_abline(slope = coef(fit.h2o)[[2]], intercept = coef(fit.h2o)[[1]],
              color = "deepskyblue4") +
  # show equation
  # stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~"))) +
  stat_regline_equation(show.legend  = FALSE)+
  mytheme_2d

# KCl based
# Plot fitted linear regression line
ggplot(df_raw_kcl, aes(x=Nitrate_input, y=NO3_mM, color=Sample_type, group=Sample_type)) +
  geom_point(size=2.5, shape=21) +
  # geom_line(size=1)+
  # geom_errorbar(aes(ymin=NO3_mM - sd_NO3_mM, ymax=NO3_mM + sd_NO3_mM), width=.05)+
  # scale_color_brewer(palette='Set2') +
  scale_color_manual(values = c("maroon2","deepskyblue4"))+
  ylab("Measured NO3- (mM) \n") +
  xlab("\n Nitrate_spike_in (mM)") +
  scale_y_continuous(breaks = seq(0,2.5,0.25), limits=c(0, 2.5))+
  scale_x_continuous(breaks = seq(0,2.1,0.1), limits=c(0, 2.1))+
  # geom_text_repel(aes(label = round(NO3_mM,3)), size = 3,family="serif", show.legend = FALSE)+
  ggtitle("KCl based Blank spike in \n") +
  geom_abline(slope = 1, intercept=0, show.legend = "y=x")+
  # regression line
  geom_abline(slope = coef(fit.kcl)[[2]], intercept = coef(fit.kcl)[[1]],
              color = "maroon2") +
  # show equation
  # stat_cor(aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~"))) +
  stat_regline_equation(show.legend  = FALSE)+
  mytheme_2d




```





