---
title: "Griess_time_series_210926"
author: "KiseokUchicago"
date: "2021-09-29"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=11, fig.height=9,
                      error=TRUE, echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE)
```

## Soil extraction method testing (Griess assay)
Researcher: **Kiseok Lee** \
Data: 9/23/21 \
Lab: **Seppe Kuehn**

```{r}
# libraries
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(vegan)
library(tidyverse)
library(magrittr)
library(readxl)
library(reshape2)
library(gtools)
library(devtools)
library(openxlsx)
library(ape)
library(stringr)
library(tidyr)

## theme for ggplot
mytheme <- theme_bw() + 
  theme(text = element_text(family="serif")) +
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=10, family="serif"))+
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank(),panel.background=element_blank(),panel.border=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))

mytheme_2d <- theme_bw() + 
  theme(text = element_text(family="serif")) +
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=13, family="serif"))+
  # theme(panel.grid.major = element_blank()) +
  # theme(panel.grid.minor = element_blank(),panel.background=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))


# color collection
my_color_collection <- c(
  "#CBD588", "#5F7FC7", "orange", "#AD6F3B", "#673770", 
  "#D14285", "#652926", "#C84248", "#8569D5", "#5E738F",
  "#D1A33D", "#8A7C64", "#599861","#616163", "#FFCDB2",
  "#6D9F71", "#242F40",
  "#CCA43B", "#F92A82", "#ED7B84", "#7EB77F", 
  "#DEC4A1", "#E5D1D0", '#0E8482', '#C9DAEA', '#337357', 
  '#95C623', '#E55812', '#04471C', '#F2D7EE', '#D3BCC0', 
  '#A5668B', '#69306D', '#0E103D', '#1A535C', '#4ECDC4', 
  '#F7FFF7', '#FF6B6B', '#FFE66D', '#6699CC', '#FFF275', 
  '#FF8C42', '#FF3C38', '#A23E48', '#000000', '#CF5C36', 
  '#EEE5E9', '#7C7C7C', '#EFC88B', '#2E5266', '#6E8898', 
  '#9FB1BC', '#D3D0CB', '#E2C044', '#5BC0EB', '#FDE74C', 
  '#9BC53D', '#E55934', '#FA7921', "#CD9BCD", "#508578", "#DA5724")

# for git push, use this instead of using wflow_git_push()
# git push -u origin master (in the Git app / in the working directory)

```

## 1. Import data table from python code
When I did the experiment, B05 and B06 was switched. D05, D06 also switched. F05, F06 switched.
```{r}
# import file
df_p1 <- openxlsx::read.xlsx("data/210928_Griess_sample_plate1.xlsx")
class(df_p1)
head(df_p1)
colnames(df_p1)

# remove NA
dim(df_p1)
df_p1 <- na.omit(df_p1)
dim(df_p1)
```

## 2. Get average and standard deviation
```{r}
# average and standard deviation
df_NO2NO3 <- df_p1 %>% group_by(Time_point, Nitrate_input, Succinate_input, Spike_in) %>% summarise(Ave_NO2_mM = mean(NO2_mM), Std_NO2_mM = sd(NO2_mM), Ave_NO2NO3_mM = mean(NO2NO3_mM), Std_NO2NO3_mM = sd(NO2NO3_mM), Ave_NO3_mM = mean(NO2NO3_mM - NO2_mM), Std_NO3_mM = sd(NO2NO3_mM - NO2_mM)) %>% ungroup()
# NO3_mM = NO2NO3_mM - NO2_mM

dim(df_NO2NO3)

# Factor in orders
# df_NO2NO3$Buffer <-  factor(df_NO2NO3$Buffer, levels = c("KCl","K2SO4","H2O"))

```

## 3. Plot - no carbon added
```{r}
# (1) Nitrite dynamics - no carbon added
colnames(df_NO2NO3)
dim(df_NO2NO3)
head(df_NO2NO3)
df_NO2NO3$Nitrate_input <- factor(df_NO2NO3$Nitrate_input)
df_no_C_added <- df_NO2NO3 %>% filter(Spike_in == "F")

ggplot(df_no_C_added, aes(x=Time_point, y=Ave_NO2_mM, color=Nitrate_input, group=Nitrate_input )) +
  geom_point(size=2.5, shape=21) +
  geom_line(size=1)+
  geom_errorbar(aes(ymin=Ave_NO2_mM - Std_NO2_mM, ymax=Ave_NO2_mM + Std_NO2_mM), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("NO2- (mM) \n") +
  xlab("\n Time point (hr)") +
  scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  ggtitle("(1) Nitrite dynamics - No carbon added \n") +
  # label
  geom_text(aes(label = round(Ave_NO2_mM,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

# (2) Nitrate dynamics - no carbon added
colnames(df_NO2NO3)
dim(df_NO2NO3)
head(df_NO2NO3)
df_NO2NO3$Nitrate_input <- factor(df_NO2NO3$Nitrate_input)
df_no_C_added <- df_NO2NO3 %>% filter(Spike_in == "F")

ggplot(df_no_C_added, aes(x=Time_point, y=Ave_NO3_mM, color=Nitrate_input, group=Nitrate_input )) +
  geom_point(size=2.5, shape=21) +
  geom_line(size=1)+
  geom_errorbar(aes(ymin=Ave_NO3_mM - Std_NO3_mM, ymax=Ave_NO3_mM + Std_NO3_mM), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("NO3- (mM) \n") +
  xlab("\n Time point (hr)") +
  # scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  ggtitle("(2) Nitrate dynamics - No carbon added \n") +
  # label
  geom_text(aes(label = round(Ave_NO3_mM,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d



```


## 4. Carbon added

```{r}
# (3) Nitrite dynamics - carbon added (Succinate)
colnames(df_NO2NO3)
dim(df_NO2NO3)
head(df_NO2NO3)
df_NO2NO3$Nitrate_input <- factor(df_NO2NO3$Nitrate_input)
df_C_added <- df_NO2NO3 %>% filter(Spike_in == "T")

ggplot(df_C_added, aes(x=Time_point, y=Ave_NO2_mM, color=Nitrate_input, group=Nitrate_input )) +
  geom_point(size=2.5, shape=21) +
  geom_line(size=1)+
  geom_errorbar(aes(ymin=Ave_NO2_mM - Std_NO2_mM, ymax=Ave_NO2_mM + Std_NO2_mM), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("NO2- (mM) \n") +
  xlab("\n Time point (hr)") +
  scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  ggtitle("(1) Nitrite dynamics - carbon added (TOC + 0.025%) \n") +
  # label
  geom_text(aes(label = round(Ave_NO2_mM,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

# (4) Nitrate dynamics - no carbon added
colnames(df_NO2NO3)
dim(df_NO2NO3)
head(df_NO2NO3)
df_NO2NO3$Nitrate_input <- factor(df_NO2NO3$Nitrate_input)
df_C_added <- df_NO2NO3 %>% filter(Spike_in == "T")

ggplot(df_C_added, aes(x=Time_point, y=Ave_NO3_mM, color=Nitrate_input, group=Nitrate_input )) +
  geom_point(size=2.5, shape=21) +
  geom_line(size=1)+
  geom_errorbar(aes(ymin=Ave_NO3_mM - Std_NO3_mM, ymax=Ave_NO3_mM + Std_NO3_mM), width=.05)+
  scale_fill_brewer(palette='Set2') +
  ylab("NO3- (mM) \n") +
  xlab("\n Time point (hr)") +
  # scale_y_continuous(breaks = seq(0,0.3,0.05), limits=c(0, 0.3))+
  ggtitle("(2) Nitrate dynamics - carbon added (TOC + 0.025%) \n") +
  # label
  geom_text(aes(label = round(Ave_NO3_mM,3)), size = 3, vjust = -1.5, family="serif", show.legend = FALSE)+
  mytheme_2d

```



