---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Welcome to Kiseok Denitrification data visualization website.

* [Soil_drying_test (9/5/21)](Soil_drying_curve.html)
* [TOC_measurement (9/11/21)](210911_TOC_measurement.html)
* [Soil_pH_test (9/14/21)](Soil_pH_method.html)
* [Soil_extraction_method_Griess (9/23/21)](Soil_extraction_method_Griess.html)
* [Griess_time_series_first_attempt_210926 (9/26/21)](Griess_time_series_210926.html)
* [Soil_extraction_2MKCl_Griess (10/5/21)](Soil_extraction_2MKCl_Griess.html)
* [Blank_extraction_2MKCl_Griess (10/7/21)](Blank_extraction_2MKCl_Griess_211007.html)
* [Testing_controls_vortex_procedures (10/8/21)](Testing_controls_vortex_procedures_211008.html)
* [211014_TOC_sample_size_test (10/13/21)](211014_TOC_sample_size_test.html)
* [211017_Griess_slurry_extraction (10/18/21)](211017_Griess_slurry_extraction.html)
* [211019_Griess_extraction_trouble_shooting (10/19/21)](211019_Griess_extraction_trouble_shooting.html)
* [211020_Griess_pipet_confirm (10/20/21)](211020_Griess_pipet_confirm.html)
* [211025_Griess_blank_decline_issue (10/25/21)](211025_Griess_blank_decline_issue.html)
* [211104_Griess_blank_decline_issue2 (10/25/21)](211104_Griess_blank_decline_issue.html)
* [211028_Griess_time_series_trial2 (10/28/21)](211028_Griess_time_series_trial2.html)
* [211127_Griess_time_series_slurry_vs_liquid_culture (11/27/21)](211127_Griess_time_series_slurry_vs_liquid_culture.html)
* [211128_Griess_time_series_3soil (11/28/21)](211128_Griess_time_series_3soil.html)
* [211220_Griess_slurry_vs_supernatant2 (12/20/21)](211220_Griess_slurry_vs_supernatant2.html)
* [211209_OD600_last_wash (12/09/21)](211209_OD600_last_wash.html)
* [211224_TOC_spikein_test + 220111 TOC filtered (12/24/21)](211224_TOC_spikein_test.html)
* [220103_Griess_pH_perturbation (1/3/22)](220103_Griess_pH_perturbation.html)
* [220106_Ammonia_method_test (1/6/22)](220106_Ammonia_method_test.html)
* [220107_Ammonia_faster (1/7/22)](220107_Ammonia_faster.html)
* [220107-2_Ammonia_tweaking (1/7/22)](220107-2_Ammonia_tweaking.html)
* [220107-3_Ammonia_30min_more (1/7/22)](220107-3_Ammonia_30min_more.html)
* [220107-4_Ammonia_5ul (1/7/22)](220107-4_Ammonia_5ul.html)
* [220107-5,6,7,8,9_Ammonia_confirm (1/7/22)](220107-5_Ammonia_confirm.html)
* [220108_Ammonia_spikein_soil_extract_direct (1/8/22)](220108_Ammonia_spikein_soil_extract_direct.html)
* [220110_Ammonia_KCl_H2O method comparison (1/10/22)](220110_Ammonia_KCl_H2O.html)
* [220111_Ammonia_dynamics (1/11/22)](220111_Ammonia_dynamics.html)
* [220113_pH_while_perturbation (1/13/22)](220113_pH_while_perturbation.html)
* [220125_pH_during_perturbation (1/25/22)](220125_pH_during_perturbation.html)
* [220126_pH_during_perturbation_mu_optT0 (1/26/22)](220126_pH_during_perturbation_mu_optT0.html)
* [220128_Griess_pH_perturbation2 (1/28/22)](220128_Griess_pH_perturbation2.html)
* [220131_pH_during_perturbation3 (1/31/22)](220131_pH_during_perturbation3.html)
* [220131_Griess_pH_perturbation3 (1/31/22)](220131_Griess_pH_perturbation3.html)
* [220210_Cuhel_et_al_2010_qPCR_data (2/10/22)](220210_Cuhel_et_al_2010_qPCR_data.html)
* [220327_Griess_3_soil_pH_perturbation (3/27/22)](220327_Griess_3_soil_pH_perturbation.html)
* [220420_Ammonia_3_soil_pH_perturbation (4/20/22)](220420_Ammonia_3_soil_pH_perturbation.html)
* [220329_pH_3soil (3/29/22)](220329_pH_3soil.html)
* [220407_pH_troubleshooting (4/7/22)](220407_pH_troubleshooting.html)
* [220414_Ammonium_compare_with_Brookside (4/14/22)](220414_Ammonium_compare_with_Brookside.html)
* [220418_Ammonium_standard_known_concentration (4/18/22)](220418_Ammonium_standard_known_concentration.html)
* [220419_Ammonium_compare_with_Brookside2 (4/19/22)](220419_Ammonium_compare_with_Brookside2.html)
* [220421_Griess_antibiotics_and_sterile (4/21/22)](220421_Griess_antibiotics_and_sterile.html)
* [220421_Ammonia_antibiotics_and_sterile (4/21/22)](220421_Ammonia_antibiotics_and_sterile.html)
* [220422_pH_half_antibiotics_sterile (4/22/22)](220422_pH_half_antibiotics_sterile.html)
* [220428_Ammonia_211128_aerobic_vs_anaerobic (4/28/22)](220428_Ammonia_211128_aerobic_vs_anaerobic.html)
* [220508_TOC_time_series + new glass 96 well plate test (5/8/22)](220508_TOC_time_series.html)
* [220513_TOC_more_time_points (5/15/22)](220513_TOC_more_time_points.html)
* [220519_Griess_antibiotics_dose_effect (5/23/22)](220519_Griess_antibiotics_dose_effect.html)
* [220520_TOC_antibiotics_dose_effect (5/24/22)](220520_TOC_antibiotics_dose_effect.html)
* [220521_pH_antibiotics_dose_effect (5/23/22)](220521_pH_antibiotics_dose_effect.html)
* [220519_Griess_crerar7_extreme_pH (5/25/22)](220519_Griess_crerar7_extreme_pH.html)
* [220526_TOC_biomass_microwave_ecoli (5/27/22)](220526_TOC_biomass_microwave_ecoli.html)
* [220527_TOC_biomass_microwave_ecoli2_30s_45s (5/28/22)](220527_TOC_biomass_microwave_ecoli2_30s_45s.html)
* [220601_TOC_biomass_microwave_control_filtered (6/1/22)](220601_TOC_biomass_microwave_filtered.html)
* [220602_TOC_biomass_microwave_microwave_filtered (6/2/22)](220602_TOC_biomass_microwave_microwave_filtered.html)
* [220603_TOC_biomass_chloroform (6/4/22)](220603_TOC_biomass_chloroform.html)
* [220606_TOC_biomass_chloroform2_large_scale (6/8/22)](220606_TOC_biomass_chloroform2_large_scale.html)



