---
title: "Soil_pH_method"
author: "KiseokUchicago"
date: "2021-09-24"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=11, fig.height=9,
                      error=TRUE, echo=TRUE, eval=TRUE, warning=FALSE, message=FALSE)
```

## Soil pH measurement method testing

Researcher: **Kiseok Lee** \
Experimental date: 9/14/21 and 9/28/21 \
Lab: **Seppe Kuehn**

```{r}
# libraries
library(dplyr)
library(ggplot2)
library(RColorBrewer)
library(vegan)
library(tidyverse)
library(magrittr)
library(readxl)
library(reshape2)
library(gtools)
library(devtools)
library(openxlsx)
library(ape)
library(stringr)
library(tidyr)

## theme for ggplot
mytheme <- theme_bw() + 
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=10, family="serif"))+
  theme(panel.grid.major = element_blank()) +
  theme(panel.grid.minor = element_blank(),panel.background=element_blank(),panel.border=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))

mytheme_2d <- theme_bw() + 
  theme(plot.title = element_text(size = 19,hjust = 0.5, family="serif")) + 
  theme(axis.title.x = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.title.y = element_text(size = 17,hjust = 0.5, family="serif")) + 
  theme(axis.text.x = element_text(hjust = 0.5, vjust=0.3,size=13, family="serif"))+
  theme(axis.text.y = element_text(size=13, family="serif"))+
  # theme(panel.grid.major = element_blank()) +
  # theme(panel.grid.minor = element_blank(),panel.background=element_blank(),plot.background=element_blank()) +
  theme(axis.ticks = element_line(size = 1.1))


# color collection
my_color_collection <- c(
  "#CBD588", "#5F7FC7", "orange", "#AD6F3B", "#673770", 
  "#D14285", "#652926", "#C84248", "#8569D5", "#5E738F",
  "#D1A33D", "#8A7C64", "#599861","#616163", "#FFCDB2",
  "#6D9F71", "#242F40",
  "#CCA43B", "#F92A82", "#ED7B84", "#7EB77F", 
  "#DEC4A1", "#E5D1D0", '#0E8482', '#C9DAEA', '#337357', 
  '#95C623', '#E55812', '#04471C', '#F2D7EE', '#D3BCC0', 
  '#A5668B', '#69306D', '#0E103D', '#1A535C', '#4ECDC4', 
  '#F7FFF7', '#FF6B6B', '#FFE66D', '#6699CC', '#FFF275', 
  '#FF8C42', '#FF3C38', '#A23E48', '#000000', '#CF5C36', 
  '#EEE5E9', '#7C7C7C', '#EFC88B', '#2E5266', '#6E8898', 
  '#9FB1BC', '#D3D0CB', '#E2C044', '#5BC0EB', '#FDE74C', 
  '#9BC53D', '#E55934', '#FA7921', "#CD9BCD", "#508578", "#DA5724")

# for git push, use this instead of using wflow_git_push()
# git push -u origin master (in the Git app / in the working directory)

```

## Another experiment from 210914
## (1) Import data
```{r}
# import file
df_pH <- openxlsx::read.xlsx("data/pH_data(9.14.21).xlsx")
class(df_pH)
df_pH <- df_pH %>% rename(Method = X1)

df_pH_gg <- melt(df_pH ,variable.name = "Solution",value.name = "pH")
# Order the method
df_pH_gg$Method <- ordered(df_pH_gg$Method, levels=c("Stand_20min", "Spin_down", "Filter_0.22um"))


# remove NA
dim(df_pH_gg)
df_pH_gg2 <- na.omit(df_pH_gg)
dim(df_pH_gg2)

```

## (2) Plot
```{r}
# plot
ggplot(df_pH_gg2, aes(x=Method, y=pH, color=Solution, group=Solution)) +
  geom_point(size=2.5, shape=21) +
  geom_line(size=1)+
  scale_fill_brewer(palette='Set2') +
  ylab("pH \n") +
  xlab("\n Settling method") +
  scale_y_continuous(breaks = seq(6,7,0.05), limits=c(6.1, 7))+
  ggtitle("pH difference by method & solution \n") +
  # label
  geom_text(aes(label = pH), size = 3, vjust = -1.5, family="serif")+
  mytheme_2d
```

## Another experiment from 210928

## (1) Import data
```{r}
# import file
df_pH <- openxlsx::read.xlsx("data/pH_data(9.28.21).xlsx")
class(df_pH)
df_pH <- df_pH %>% rename(Method = X1)

df_pH_gg <- melt(df_pH ,variable.name = "Solution",value.name = "pH")
# Order the method
df_pH_gg$Method <- ordered(df_pH_gg$Method, levels=c("Stand_20min", "Spin_down", "Filter_0.22um", "Whatman"))


# remove NA
dim(df_pH_gg)

```

## 2. Plot
```{r}
# plot
ggplot(df_pH_gg, aes(x=Method, y=pH, color=Solution, group=Solution)) +
  geom_point(size=2.5, shape=21) +
  geom_line(size=1)+
  scale_fill_brewer(palette='Set2') +
  ylab("pH \n") +
  xlab("\n Settling method") +
  scale_y_continuous(breaks = seq(5,7,0.1), limits=c(5, 7))+
  ggtitle("pH difference by method & solution \n") +
  # label
  geom_text(aes(label = pH), size = 3, vjust = -1.5, family="serif", show.legend  = FALSE)+
  mytheme_2d
```



